// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SistemaVeiculos.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231126174447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEST")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CFOP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CapPotCilVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CategoriaVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChassiVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CombustivelVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EmissaoDocumentoVeiculo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EspecieVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExerEmisDocVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("FabricacaoVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("Grupo")
                        .HasColumnType("int");

                    b.Property<string>("LocalRegistroVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MarcaModeloVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Margem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ModeloVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrCusto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrVenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PrVendaPrazo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegistroVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RenavamVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RntrcVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ViaReciboVeiculo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("Foto", b =>
                {
                    b.HasOne("Veiculo", "Veiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Veiculo", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
